// Dataset de Inteligencia Marítima Asia-México y Taiwán
// Generado por el Motor Cuantamental IN2TECHMX

const SHIPPING_KPIS = {
  "spotFeuShanghai": 4420.0,
  "spotFeuKaohsiung": 4680.0,
  "spotTeuStandard": 2850.0,
  "weeklyChangePct": -1.45,
  "taiwanStraitTension": "MODERADA-ALTA",
  "taiwanStraitTensionIndex": 6.8,
  "averageTransitDays": 22.4,
  "congestionDaysManzanillo": 4.8,
  "baseOceanFreight": 3460.0,
  "bunkerBafSurcharge": 620.0,
  "warRiskInsuranceSurcharge": 350.0,
  "peakSeasonSurcharge": 250.0,
  "bunkerFuelVlsfoUsdTon": 645.0,
  "probSpikeAbove6000": 8.45,
  "probDropBelow4000": 26.3,
  "lastUpdate": "2026-10-05 17:48:34"
};

const WEEKLY_HORIZONS = [
  {
    "week": 1,
    "day": 7,
    "date": "2026-10-12",
    "title": "SEMANA 1 (Próximos 7 Días)",
    "catalyst": "Ventana post-feriados: despacho de órdenes y espacios abiertos",
    "p50_feu": 4469.0,
    "p50_teu": 2860.0,
    "diff_usd": -211.0,
    "diff_pct": -4.5,
    "diff_label": "VENTANA DE OPORTUNIDAD",
    "diff_class": "val-emerald",
    "range_p25_p75": "$4,267 - $4,731",
    "range_p10_p90": "$4,127 - $4,975",
    "p90_risk": "$4,975",
    "transit_days": "21 - 23 días",
    "recommendation": "COMPRA RECOMENDADA (VENTANA ÓPTIMA): Las tarifas tocan su piso mensual ($4,469 USD). Conviene cerrar bookings antes del ciclo decembrino."
  },
  {
    "week": 2,
    "day": 14,
    "date": "2026-10-19",
    "title": "SEMANA 2 (En 14 Días)",
    "catalyst": "Renovación quincenal de contratos y ajuste de combustible búnker",
    "p50_feu": 4844.0,
    "p50_teu": 3100.0,
    "diff_usd": 164.0,
    "diff_pct": 3.5,
    "diff_label": "ALZA MODERADA (+3.5%)",
    "diff_class": "val-cyan",
    "range_p25_p75": "$4,567 - $5,222",
    "range_p10_p90": "$4,375 - $5,602",
    "p90_risk": "$5,602",
    "transit_days": "22 - 25 días",
    "recommendation": "ÚLTIMA LLAMADA A TARIFA ESTÁNDAR: El flete sube a $4,844 USD. Si tu carga zarpa a mediados de mes, asegura espacio hoy."
  },
  {
    "week": 3,
    "day": 21,
    "date": "2026-10-26",
    "title": "SEMANA 3 (En 21 Días)",
    "catalyst": "Comienzo del ciclo pre-navideño y presión de bodega hacia México",
    "p50_feu": 5265.0,
    "p50_teu": 3370.0,
    "diff_usd": 585.0,
    "diff_pct": 12.5,
    "diff_label": "PRESIÓN DECEMBRINA (+12.5%)",
    "diff_class": "val-amber",
    "range_p25_p75": "$4,930 - $5,739",
    "range_p10_p90": "$4,697 - $6,241",
    "p90_risk": "$6,241",
    "transit_days": "23 - 26 días",
    "recommendation": "PRECAUCIÓN Y SOBRECOSTO: El flete rompe los $5,265 USD por saturación naviera. Si no reservaste, contrata forward para evitar saltos P90 ($5,860+)."
  },
  {
    "week": 4,
    "day": 30,
    "date": "2026-11-04",
    "title": "SEMANA 4 (Horizonte a 1 Mes)",
    "catalyst": "Pico de saturación en Manzanillo y recargo por temporada alta (PSS)",
    "p50_feu": 5780.0,
    "p50_teu": 3699.0,
    "diff_usd": 1100.0,
    "diff_pct": 23.5,
    "diff_label": "PICO DE SATURACIÓN (+23.5%)",
    "diff_class": "val-rose",
    "range_p25_p75": "$5,382 - $6,364",
    "range_p10_p90": "$5,106 - $7,013",
    "p90_risk": "$7,013",
    "transit_days": "24 - 28 días",
    "recommendation": "TEMPORADA CRÍTICA CARA: Flete en $5,780 USD con riesgo de choque P90 en $6,530 USD. Fondeo en Manzanillo sube a 6+ días. Evitar compras spot."
  }
];

const SHIPPING_TRAJECTORY = [
  {
    "day": 0,
    "date": "2026-10-05",
    "label": "Base",
    "p10": 4559.0,
    "p25": 4608.0,
    "p50": 4680.0,
    "p75": 4762.0,
    "p90": 4823.0,
    "catalyst": "Cotización Spot Observada (Shanghai/Kaohsiung a Manzanillo)"
  },
  {
    "day": 1,
    "date": "2026-10-06",
    "label": "Día 1",
    "p10": 4479.0,
    "p25": 4549.0,
    "p50": 4650.0,
    "p75": 4771.0,
    "p90": 4867.0,
    "catalyst": "Post-Golden Week China; despacho de órdenes acumuladas"
  },
  {
    "day": 2,
    "date": "2026-10-07",
    "label": "Día 2",
    "p10": 4410.0,
    "p25": 4496.0,
    "p50": 4620.0,
    "p75": 4771.0,
    "p90": 4897.0,
    "catalyst": "Disponibilidad de espacios en buques transpacíficos"
  },
  {
    "day": 3,
    "date": "2026-10-08",
    "label": "Día 3",
    "p10": 4348.0,
    "p25": 4447.0,
    "p50": 4590.0,
    "p75": 4767.0,
    "p90": 4920.0,
    "catalyst": "Monitoreo de ejercicios aeronavales en el Estrecho de Taiwán"
  },
  {
    "day": 4,
    "date": "2026-10-09",
    "label": "Día 4",
    "p10": 4289.0,
    "p25": 4400.0,
    "p50": 4560.0,
    "p75": 4761.0,
    "p90": 4938.0,
    "catalyst": "Flujos regulares de manufactura y electrónica de exportación"
  },
  {
    "day": 5,
    "date": "2026-10-10",
    "label": "Día 5",
    "p10": 4234.0,
    "p25": 4355.0,
    "p50": 4530.0,
    "p75": 4753.0,
    "p90": 4953.0,
    "catalyst": "Rotación de vacíos y disponibilidad de equipo en Kaohsiung"
  },
  {
    "day": 6,
    "date": "2026-10-11",
    "label": "Día 6",
    "p10": 4179.0,
    "p25": 4310.0,
    "p50": 4499.0,
    "p75": 4742.0,
    "p90": 4965.0,
    "catalyst": "Cierre semanal; consolidación de bookings hacia Manzanillo"
  },
  {
    "day": 7,
    "date": "2026-10-12",
    "label": "Día 7",
    "p10": 4127.0,
    "p25": 4267.0,
    "p50": 4469.0,
    "p75": 4731.0,
    "p90": 4975.0,
    "catalyst": "Reporte quincenal de congestión portuaria en México"
  },
  {
    "day": 8,
    "date": "2026-10-13",
    "label": "Día 8",
    "p10": 4160.0,
    "p25": 4308.0,
    "p50": 4523.0,
    "p75": 4804.0,
    "p90": 5068.0,
    "catalyst": "Actualización de recargo por combustible BAF indexado al crudo"
  },
  {
    "day": 9,
    "date": "2026-10-14",
    "label": "Día 9",
    "p10": 4193.0,
    "p25": 4350.0,
    "p50": 4576.0,
    "p75": 4874.0,
    "p90": 5159.0,
    "catalyst": "Evaluación de tránsito en Estrecho de Formosa vs Desvío Bashi"
  },
  {
    "day": 10,
    "date": "2026-10-15",
    "label": "Día 10",
    "p10": 4229.0,
    "p25": 4393.0,
    "p50": 4630.0,
    "p75": 4945.0,
    "p90": 5250.0,
    "catalyst": "Programación de salidas (Blank Sailings) de consorcios navieros"
  },
  {
    "day": 11,
    "date": "2026-10-16",
    "label": "Día 11",
    "p10": 4264.0,
    "p25": 4435.0,
    "p50": 4683.0,
    "p75": 5015.0,
    "p90": 5339.0,
    "catalyst": "Operaciones logísticas estándar en corredor transpacífico"
  },
  {
    "day": 12,
    "date": "2026-10-17",
    "label": "Día 12",
    "p10": 4301.0,
    "p25": 4479.0,
    "p50": 4737.0,
    "p75": 5084.0,
    "p90": 5427.0,
    "catalyst": "Arribos escalonados a fondeadero de Manzanillo"
  },
  {
    "day": 13,
    "date": "2026-10-18",
    "label": "Día 13",
    "p10": 4337.0,
    "p25": 4522.0,
    "p50": 4790.0,
    "p75": 5153.0,
    "p90": 5514.0,
    "catalyst": "Renovación de contratos forward spot de navieras asiáticas"
  },
  {
    "day": 14,
    "date": "2026-10-19",
    "label": "Día 14",
    "p10": 4375.0,
    "p25": 4567.0,
    "p50": 4844.0,
    "p75": 5222.0,
    "p90": 5602.0,
    "catalyst": "Cierre de Semana 2; balance de capacidad de bodega"
  },
  {
    "day": 15,
    "date": "2026-10-20",
    "label": "Día 15",
    "p10": 4420.0,
    "p25": 4618.0,
    "p50": 4904.0,
    "p75": 5296.0,
    "p90": 5694.0,
    "catalyst": "Monitoreo de inventarios en hubs tecnológicos de Taiwán (Hsinchu)"
  },
  {
    "day": 16,
    "date": "2026-10-21",
    "label": "Día 16",
    "p10": 4465.0,
    "p25": 4669.0,
    "p50": 4964.0,
    "p75": 5371.0,
    "p90": 5787.0,
    "catalyst": "Flujos comerciales de componentes automotrices y nearshoring hacia México"
  },
  {
    "day": 17,
    "date": "2026-10-22",
    "label": "Día 17",
    "p10": 4511.0,
    "p25": 4721.0,
    "p50": 5024.0,
    "p75": 5445.0,
    "p90": 5878.0,
    "catalyst": "Verificación de primas de riesgo bélico en aseguradoras navales"
  },
  {
    "day": 18,
    "date": "2026-10-23",
    "label": "Día 18",
    "p10": 4557.0,
    "p25": 4772.0,
    "p50": 5084.0,
    "p75": 5518.0,
    "p90": 5969.0,
    "catalyst": "Desalojo aduanal y disponibilidad ferroviaria en Lázaro Cárdenas"
  },
  {
    "day": 19,
    "date": "2026-10-24",
    "label": "Día 19",
    "p10": 4604.0,
    "p25": 4825.0,
    "p50": 5145.0,
    "p75": 5593.0,
    "p90": 6061.0,
    "catalyst": "Actualización de índices FBX y SCFI Asia-América Latina"
  },
  {
    "day": 20,
    "date": "2026-10-25",
    "label": "Día 20",
    "p10": 4651.0,
    "p25": 4877.0,
    "p50": 5205.0,
    "p75": 5666.0,
    "p90": 6152.0,
    "catalyst": "Cierre de Semana 3; acumulación de carga previa a fin de mes"
  },
  {
    "day": 21,
    "date": "2026-10-26",
    "label": "Día 21",
    "p10": 4697.0,
    "p25": 4930.0,
    "p50": 5265.0,
    "p75": 5739.0,
    "p90": 6241.0,
    "catalyst": "Inspección de capacidad en terminales de Ningbo y Shenzhen"
  },
  {
    "day": 22,
    "date": "2026-10-27",
    "label": "Día 22",
    "p10": 4742.0,
    "p25": 4979.0,
    "p50": 5322.0,
    "p75": 5809.0,
    "p90": 6328.0,
    "catalyst": "Dinámica de tarifas de flete y recargos por temporada alta (PSS)"
  },
  {
    "day": 23,
    "date": "2026-10-28",
    "label": "Día 23",
    "p10": 4786.0,
    "p25": 5029.0,
    "p50": 5379.0,
    "p75": 5879.0,
    "p90": 6414.0,
    "catalyst": "Flujos de importación acelerada por fricciones arancelarias"
  },
  {
    "day": 24,
    "date": "2026-10-29",
    "label": "Día 24",
    "p10": 4832.0,
    "p25": 5080.0,
    "p50": 5437.0,
    "p75": 5949.0,
    "p90": 6501.0,
    "catalyst": "Operaciones marítimas ordinarias sin bloqueos en estrecho"
  },
  {
    "day": 25,
    "date": "2026-10-30",
    "label": "Día 25",
    "p10": 4877.0,
    "p25": 5129.0,
    "p50": 5494.0,
    "p75": 6019.0,
    "p90": 6587.0,
    "catalyst": "Evaluación de tiempos de espera en muelles de México"
  },
  {
    "day": 26,
    "date": "2026-10-31",
    "label": "Día 26",
    "p10": 4922.0,
    "p25": 5179.0,
    "p50": 5551.0,
    "p75": 6088.0,
    "p90": 6673.0,
    "catalyst": "Planificación de bookings para embarques de noviembre"
  },
  {
    "day": 27,
    "date": "2026-11-01",
    "label": "Día 27",
    "p10": 4968.0,
    "p25": 5230.0,
    "p50": 5608.0,
    "p75": 6157.0,
    "p90": 6758.0,
    "catalyst": "Ajuste de tarifas de navieras para inicio de mes siguiente"
  },
  {
    "day": 28,
    "date": "2026-11-02",
    "label": "Día 28",
    "p10": 5013.0,
    "p25": 5280.0,
    "p50": 5665.0,
    "p75": 6226.0,
    "p90": 6843.0,
    "catalyst": "Rebalanceo de contenedores vacíos entre Asia y América"
  },
  {
    "day": 29,
    "date": "2026-11-03",
    "label": "Día 29",
    "p10": 5060.0,
    "p25": 5331.0,
    "p50": 5723.0,
    "p75": 6296.0,
    "p90": 6928.0,
    "catalyst": "Horizonte final a 30 días de proyección logística"
  },
  {
    "day": 30,
    "date": "2026-11-04",
    "label": "Día 30",
    "p10": 5106.0,
    "p25": 5382.0,
    "p50": 5780.0,
    "p75": 6364.0,
    "p90": 7013.0,
    "catalyst": "Dinámica logística ordinaria"
  }
];

const HISTORICAL_SHOCKS = [
  {
    "event": "Crisis Mar Rojo & Desvío Cabo Buena Esperanza",
    "date": "2024-01-15",
    "impact_feu_usd": "+$3,200 USD",
    "change_pct": "+112.5%",
    "transmission": "Efecto dominó global: buques desviados absorbieron 12% de la capacidad mundial de flota, disparando fletes hacia México."
  },
  {
    "event": "Maniobras Militares PLA tras visita Pelosi a Taiwán",
    "date": "2022-08-04",
    "impact_feu_usd": "+$1,450 USD",
    "change_pct": "+24.8%",
    "transmission": "Cierre temporal de 6 zonas marítimas en el Estrecho; buques desviados al este sumaron 3 días de tránsito y primas de guerra."
  },
  {
    "event": "Lockdown Sanitario Puerto de Shanghai",
    "date": "2022-04-12",
    "impact_feu_usd": "+$2,800 USD",
    "change_pct": "+41.3%",
    "transmission": "Parálisis de camiones de carga y acumulación de 300 buques en fondeadero con escasez masiva de contenedores vacíos."
  },
  {
    "event": "Restricción de Calado en Canal de Panamá (Sequía)",
    "date": "2023-11-20",
    "impact_feu_usd": "+$1,850 USD",
    "change_pct": "+35.2%",
    "transmission": "Carga desviada a puertos del Pacífico mexicano (Manzanillo / Lázaro Cárdenas), saturando patios portuarios."
  }
];

const RECENT_SHIPPING_NEWS = [
  {
    "id": "SHIP-03cbe247",
    "title": "Point Roberts, el pueblo de EEUU que podría desaparecer por la guerra comercial entre Trump y Canadá",
    "source": "El Economista",
    "url": "https://news.google.com/rss/articles/CBMi-AFBVV95cUxObVhFOFpEdUJ1bzM1SV9PMUgzUERiNWVSa2pkMlVPVkZOMXBPYUwyTnV6T2MxRFd5MV93WGNhTUFvb01rZ2FnZ0RYal9uWnk3Tmk4bVZkYmZ2UVVrdm81VTRBb2c3a2VjUHlvT0NVcTlheDNyYnBwOW1WcXpFOThYRTRuTldObk0yX0doSzNGangtYnA4X015R1hIQkFWRDRnSG4yZG5XeW91UnZXOGpHV0Q0VWVTa0V0MnJtLVU0VTIyMkhfOGlZeUZRSEZBd2VKZmk1dmhmMkFrWVVITHVFVTVIMUhmcXlDRUVoaVE1OWVONDNlR0dkRg?oc=5",
    "date": "2026-10-05",
    "channel": "fricciones_geopoliticas",
    "channel_ui": "⚖️ Fricciones China-Occidente",
    "direction": "ALCISTA_FLETE",
    "impact_score": 8.6,
    "impact_level": "CRÍTICO",
    "impact_badge": "badge-critico",
    "transmission": "Aranceles de EE.UU. a China aceleran embarques masivos (front-loading) hacia México para nearshoring, saturando la capacidad de bodega y encareciendo fletes spot."
  },
  {
    "id": "SHIP-02e80c2e",
    "title": "Los líderes europeos se creyeron muy listos con los aranceles pero China es un monstruo dispuesto a arrasar con todo",
    "source": "Híbridos y Eléctricos",
    "url": "https://news.google.com/rss/articles/CBMi8wFBVV95cUxOaUhOSlJ4M1VNVE0xYnJlZmZQUlNjYmIxWVZhSDBkV0V6cUxXUnIxUGwxZklCMmxtbG9zZi1udmU1akhxSjZoRlRDb3Z1UTY1MThmdVpyWHJrbENHZ1p3a2p1V3hzQ1pxeGU4Njk3SlJFOVU4SmRsTXd0RXNVdV9mZFZRMWNQRXg3WGRsVnV5WTlBdUo5MkQtUVNQY0Q0cU1WR2dvYmhzY29CbnRMVm1yTkJ1UTczZXU0Wm9SeDYtd2hDZGdrbElsQzRmc3NGVjdYSXMyeXV1OGs2OFlwbzlSWVlfTXFJYm5EWm9FZzJ5RFRCdGc?oc=5",
    "date": "2026-10-05",
    "channel": "china_ports",
    "channel_ui": "🇨🇳 China & Exportaciones",
    "direction": "ALCISTA_FLETE",
    "impact_score": 7.3,
    "impact_level": "ALTO",
    "impact_badge": "badge-alto",
    "transmission": "Fuerte demanda de zarpes o restricciones de espacio en puertos de Shanghai/Ningbo impulsan tarifas spot al alza."
  },
  {
    "id": "SHIP-027587cb",
    "title": "Maersk implementa recargo por temporada alta en rutas de Sudamérica a Norteamérica",
    "source": "Data Portuaria",
    "url": "https://news.google.com/rss/articles/CBMi1wFBVV95cUxOWnlYN3ZZTVBTZ2ppRGVaaWExSXlGVlJ5MnY1MWVvQXYxeGNNSERJUmZhcUY5b3YxODM5dFlFR1lGYlF1UXBRS0o3UkIxZkdLSm9BOXJmX1l4ejVXV3gzMEhOMWlQR2R2R0xoMkZZTWZXbnRpM05YanpVZ0V5NzRrU3I5NHdyWDdXNHUyOUFJMU9wT2RteG1PMFVCZHlvVUM2NEZ0bVBIQ3g3djVmQTJSRFRta2hlWTFKcWZvSG5hS2l6cGR0Z0xqTElEcG9qQ0FzSGQ5WlROcw?oc=5",
    "date": "2026-10-05",
    "channel": "shipping_lines",
    "channel_ui": "🚢 Navieras & Contenedores",
    "direction": "ALCISTA_FLETE",
    "impact_score": 7.3,
    "impact_level": "ALTO",
    "impact_badge": "badge-alto",
    "transmission": "Navieras aplican recargos generales (GRI) o cancelaciones de salidas (blank sailings) para sostener tarifas elevadas."
  },
  {
    "id": "SHIP-057da3e8",
    "title": "Las exportaciones de petróleo del Golfo vuelven a niveles previos a la guerra pese al bloqueo de Ormuz",
    "source": "Yahoo Finanzas",
    "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxNcVJMbHRtVG9LRGhMdnA3OEZkWmxSbWVrOFpjT2YxbXlNUzRqVlJ2YXJldkh3WTFkaDBwbGJqV0pkV1ppS2ZuQ1FrNk9yQlFod0NScmtqQU1TS2FxTnR1ejFPTnNBRXRnY3J1OVdIX1ZOaU9WRlY3WGc1UTZBdFNlQTFmM2lYYmFheXc3UHJHMmVJTENvRWhmX3JRYzdEak9DVDdBbzV6cEM4UQ?oc=5",
    "date": "2026-10-05",
    "channel": "petroleo_bunker",
    "channel_ui": "🛢️ Petróleo & Combustible Bunker",
    "direction": "ALCISTA_FLETE",
    "impact_score": 6.8,
    "impact_level": "ALTO",
    "impact_badge": "badge-alto",
    "transmission": "Alza del petróleo incrementa el precio del combustible marino (VLSFO); navieras indexan recargos BAF (+180 a +350 USD/FEU) y reducen velocidad (slow-steaming +2d)."
  },
  {
    "id": "SHIP-0438b502",
    "title": "Cómo la guerra comercial entre Estados Unidos y Canadá puede afectar a los inversiones",
    "source": "Yahoo",
    "url": "https://news.google.com/rss/articles/CBMilgFBVV95cUxQRWRmUFVNTjJ1aWFic3N4N2hOc3RNSEUzZC1PT3Y3X29nQldIZzdHekpVOGJ2d1ZpZGY4Rkh4WXl5MU52RWRwb082SmVERUQwa2NVcmJqcklKbW0tT2tTUlFCdXJWVzdPUXFqRXdZM2J0dGZkbm1zWWpZekJsWVU3bUQydmNEOTBLNGQ0djB4LXYzZFREWWc?oc=5",
    "date": "2026-10-05",
    "channel": "fricciones_geopoliticas",
    "channel_ui": "⚖️ Fricciones China-Occidente",
    "direction": "ALCISTA_FLETE",
    "impact_score": 6.8,
    "impact_level": "ALTO",
    "impact_badge": "badge-alto",
    "transmission": "Aranceles de EE.UU. a China aceleran embarques masivos (front-loading) hacia México para nearshoring, saturando la capacidad de bodega y encareciendo fletes spot."
  },
  {
    "id": "SHIP-03b2a8ed",
    "title": "Confiabilidad de los itinerarios de portacontenedores en Asia cae 32,3% debido a la congestión portuaria",
    "source": "Mundo Marítimo",
    "url": "https://news.google.com/rss/articles/CBMi1wFBVV95cUxPTHRwMGlrdV9BczRZTGtlMEVsbHpfNkpVQ3NIRDgxNGROXzIxZW14a1piRUtjY042UEtFckFYQWFLNmxUR0xTZnctRWN6cmJUSE00aFFBUHp2TTM3VFJNWlhTaDRXRDVlaFhwQUhiWmZpYXFsYk9zNTF6OENkQUFQVGVKYzVObTc0dzF6Y3REQkNLcGxGUnFWRm54RkNOOXBXLUNJUGRNNm9WenJDVE40TzBWMGc1RjVQdUJnUC1XQ0h1YVlkcVNCOGNmXzZNQUl0Wmt2Vlg4Zw?oc=5",
    "date": "2026-10-05",
    "channel": "china_ports",
    "channel_ui": "🇨🇳 China & Exportaciones",
    "direction": "ALCISTA_FLETE",
    "impact_score": 6.2,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Fuerte demanda de zarpes o restricciones de espacio en puertos de Shanghai/Ningbo impulsan tarifas spot al alza."
  },
  {
    "id": "SHIP-0136ea92",
    "title": "Las bolsas de valores de Taiwán cerraron con subidas; el Taiwan Weighted ganó un 2.46%",
    "source": "Investing.com México",
    "url": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxPclpTRDRscTVyUmpmODdrMjd4bUZ2WENmQ2FEUzZZYTRKdlc3UTlqMnR0eVl6YUV5VmFhX3d3UTZUdWtBS183elFpZDR4ZldKTEliVlNybnNlR2dNZHVUcExMdUV4MUZDY0k0ZG5EUDlRay1MZklMcW5sWU9QbVItdUs2MkVsdVAyN1ZiZEEwVTQyaTg1dTJmbGFFUFIzanVEck1ZTnIyeEllQlctdFp3S3lqV3RIZ0JGQ09RNjM3Z2ViMEsyRzdPY0hXdGw3bWJZWXdsLUR3?oc=5",
    "date": "2026-10-05",
    "channel": "taiwan_strait",
    "channel_ui": "🇹🇼 Taiwán & Estrecho",
    "direction": "NEUTRAL",
    "impact_score": 5.7,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Monitoreo continuo de operaciones aeronavales en el estrecho sin interrupción de itinerarios comerciales."
  },
  {
    "id": "SHIP-00e12296",
    "title": "Evergreen Marine Corporation (Taiwan) Ltd. : Masterlink Securities es neutral",
    "source": "MarketScreener España",
    "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxNQkx0RmE5bFViV09FLTZ1SnZOOHFsZHpBaTcxQVdIY0JiVzVnbnpaRW96bTR5VERsdGxmZkJsdlhoRVM1X0labmp3eHBiUHNPRm95SXZRWDEzeG5YV1Z4SVJvZ3E5cER5TEZWMVNUbDgxZDJtSnNBRy0zaHpXSC1DOGROWENHUkNkZ3hRMXVSQW01anBCWUdNNkNmSEprWGNjbzBFWkRYby1wbnVTaHRDOS1henN5a3dJcElWRXRlUVR6VXFsamFV?oc=5",
    "date": "2026-10-05",
    "channel": "taiwan_strait",
    "channel_ui": "🇹🇼 Taiwán & Estrecho",
    "direction": "NEUTRAL",
    "impact_score": 5.7,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Monitoreo continuo de operaciones aeronavales en el estrecho sin interrupción de itinerarios comerciales."
  },
  {
    "id": "SHIP-03a726b7",
    "title": "Chinese Taipei – China marcadores y predicciones",
    "source": "Sofascore",
    "url": "https://news.google.com/rss/articles/CBMijAFBVV95cUxNUk93bU1FMnZVTDF4RjA0M1g0eFZSOHhqejZKOTZLOTN0b1V6RWpDUEpTUUNKc2xMQXdLeXBDckJwcTZYTUJyVUZQVEQ2UW44LVdIUTc0a2g3dUZNMzhrYWEwX2p6Y0pVd3JlUk1NX1daNlluYjdRTlVRQkROc2xJbF9GS1NZZ25fMEtkZw?oc=5",
    "date": "2026-10-05",
    "channel": "taiwan_strait",
    "channel_ui": "🇹🇼 Taiwán & Estrecho",
    "direction": "NEUTRAL",
    "impact_score": 5.7,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Monitoreo continuo de operaciones aeronavales en el estrecho sin interrupción de itinerarios comerciales."
  },
  {
    "id": "SHIP-032873dd",
    "title": "Controversia en Alemania con la traducción de «Taiwan Travelogue»: Lin Yu-li asume la interpretación y Yang Shuang-zi defiende el vínculo entre literatura y política",
    "source": "rti.org.tw",
    "url": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE9PUWJoNnEyelhRSnI1OVVKdHhJencwbGgxYzBMbVZvMlc2VUtpRE5pSlVRcTh2VUNqbnJrel90TWsxeTRsYkxxVzlJRlNCLUQ0dm9VQ29PZjN6UFU?oc=5",
    "date": "2026-10-05",
    "channel": "taiwan_strait",
    "channel_ui": "🇹🇼 Taiwán & Estrecho",
    "direction": "NEUTRAL",
    "impact_score": 5.7,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Monitoreo continuo de operaciones aeronavales en el estrecho sin interrupción de itinerarios comerciales."
  },
  {
    "id": "SHIP-057749c3",
    "title": "Stock market outlook today, 5 Oct: Sensex, Nifty prediction - DJIA, S&P, NASDAQ, GIFT Nifty, Nikkei, Taiwan cues",
    "source": "TradingView",
    "url": "https://news.google.com/rss/articles/CBMi7wFBVV95cUxPVVJnRFhjNFpwZTgwOHJjaV9OTmtRSzNZRkhyYlRyZkZsY1ltaEItYWhub0tiN0dNMlNzUlBtM0VhZnhqWVhBbzB5c3BiOThsdHQwbmpYdGN3SmUxaEFsanZDVmFpczZVdjI4NUVHY29QYnhhNFItdTNUbldJUmtCbDAwbGFZcGFLczNMNHdXR2RadXdBbDQycjV2My1NcnExODdmMnNiUTYtR2IyVUpJLWlaRnZ0VDRfRkhMdndsTVRXVlFISTdBVTRsM3NwdFJMMWw4OUVNRDdQSEsxbFo3S3BMaHJmZG5sVTlXb1dVZw?oc=5",
    "date": "2026-10-05",
    "channel": "taiwan_strait",
    "channel_ui": "🇹🇼 Taiwán & Estrecho",
    "direction": "NEUTRAL",
    "impact_score": 5.7,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Monitoreo continuo de operaciones aeronavales en el estrecho sin interrupción de itinerarios comerciales."
  },
  {
    "id": "SHIP-0417162d",
    "title": "China abre una investigación antidumping a la importación de un químico desde la UE",
    "source": "France 24",
    "url": "https://news.google.com/rss/articles/CBMi5gFBVV95cUxOaDVvSFZOUTE1TXJnM2lRczN1V0RINm80ZlhUcTF1YnRCTF95NW9tcnY2NV9zWHRuZ0l3ZmVtck5kZEpUamZyOUk3dUtWaWFoaldmaFpuUV9SakRzejBBRml3eEtQYWkxYnNvNU9aQzlFb0tEcEV1YmtXTnpNZDRJSjMtS3l6TllHMFRMQWpVQVlVbjNlUHYxeHZwbDNfeUZhQTE3TUlHODRDUHZkU2oza1BtRm1EQ0hjZ2xJVUg0WWpYSFhzYWFYbU5PcGZWc3BLLTZZMDRTVDFlVlBabC1fV3NqOUhtQQ?oc=5",
    "date": "2026-10-05",
    "channel": "china_ports",
    "channel_ui": "🇨🇳 China & Exportaciones",
    "direction": "NEUTRAL",
    "impact_score": 5.7,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Operaciones de carga y zarpe en terminales chinas operando en régimen estándar de calendario."
  },
  {
    "id": "SHIP-05425aba",
    "title": "Estudiantes de Hai Phong ganan el primer premio en el Concurso de Pintura Infantil 2026 organizado por la ciudad de Ningbo (China).",
    "source": "Vietnam.vn",
    "url": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxPVzJvUHpDRlVZU0M2VXo1VnlFbWNjcEVVcl9icVJxWmxiZm02aGV1VWRpQW1LazlQVXNNdDhXZnNKZWMySWdnWkc1Szc4ZUxWZmRVbGFibTlBUEhlUzZxUndPTmZYTldPcU1mckZzcG5tOE9UbG9pcURnRDZHWHdpaHE2eTk3LS10clN6ZzNQQ0xBUDd5aGJCX2s1U3RKX2ZfaGpJY250MlpHNUdHTWtDbmFXTTZUVWVKM1ZnN2V1WUg?oc=5",
    "date": "2026-10-05",
    "channel": "china_ports",
    "channel_ui": "🇨🇳 China & Exportaciones",
    "direction": "NEUTRAL",
    "impact_score": 5.7,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Operaciones de carga y zarpe en terminales chinas operando en régimen estándar de calendario."
  },
  {
    "id": "SHIP-046bbcd5",
    "title": "Carrera Manzanillo 2026: 5 mil personas correrán dentro del puerto comercial más importante de México",
    "source": "24 HORAS | El Diario sin Límites",
    "url": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxPUkd0MnN2RWZIYkpmN0lxOEJGTFVJdWRhZU9OS3czcU9DdDVPdjJlSFRVWUtlUVVwYl91S05Ga0FxT3o5SWVUelgxbzB3aVlOMHp5MWZEMkRveHVoWHpNRWR2TlhTR2kxZGZOdDRDYTRTZFdLWkplWl9la3FBZ0ZQa3NzcEJ4Z3ZiZTNrZ3ZtYnMxaEN1RUNQMHFiaXhqc0ZDbl90Yjl1azBBM1pCekRxdzJydmZ0VEJ1Q2RSM1p5b3dJTDBtX3NHWQ?oc=5",
    "date": "2026-10-05",
    "channel": "mexico_ports",
    "channel_ui": "🇲🇽 México & Manzanillo",
    "direction": "NEUTRAL",
    "impact_score": 5.7,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Tiempos de fondeo y desalojo aduanal en rangos históricos promedio (4 a 6 días)."
  },
  {
    "id": "SHIP-00e12296",
    "title": "Evergreen Marine Corporation (Taiwan) Ltd. : Masterlink Securities es neutral",
    "source": "MarketScreener España",
    "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxNQkx0RmE5bFViV09FLTZ1SnZOOHFsZHpBaTcxQVdIY0JiVzVnbnpaRW96bTR5VERsdGxmZkJsdlhoRVM1X0labmp3eHBiUHNPRm95SXZRWDEzeG5YV1Z4SVJvZ3E5cER5TEZWMVNUbDgxZDJtSnNBRy0zaHpXSC1DOGROWENHUkNkZ3hRMXVSQW01anBCWUdNNkNmSEprWGNjbzBFWkRYby1wbnVTaHRDOS1henN5a3dJcElWRXRlUVR6VXFsamFV?oc=5",
    "date": "2026-10-05",
    "channel": "shipping_lines",
    "channel_ui": "🚢 Navieras & Contenedores",
    "direction": "NEUTRAL",
    "impact_score": 5.7,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Mantenimiento de tarifas de flete marítimo dentro de los contratos de servicio vigentes."
  },
  {
    "id": "SHIP-018fa881",
    "title": "Maersk y CMA CGM terminan cooperación en la ruta Asia-Sudamérica",
    "source": "MasContainer",
    "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxPZnlxNFRYZlZOdjZKODhmeE1RM1V5MjE1MmFoc3hyeFNCaEdxT3VseDF0eURWaHlpeFh4dmM3R2NNSnhUOUt2S1l3VG96LTNZLVZtYjdiSDF4dTlfY05HUWxVTUE4TUNCLXRka1RtVnlPWmlqcEJPWFlFMTRYdjN4QjRkbXVkQ2JWWGN2NXBJYlhOQVluN0twb3BNSEh5dw?oc=5",
    "date": "2026-10-05",
    "channel": "shipping_lines",
    "channel_ui": "🚢 Navieras & Contenedores",
    "direction": "NEUTRAL",
    "impact_score": 5.7,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Mantenimiento de tarifas de flete marítimo dentro de los contratos de servicio vigentes."
  },
  {
    "id": "SHIP-0417162d",
    "title": "China abre una investigación antidumping a la importación de un químico desde la UE",
    "source": "France 24",
    "url": "https://news.google.com/rss/articles/CBMi5gFBVV95cUxOaDVvSFZOUTE1TXJnM2lRczN1V0RINm80ZlhUcTF1YnRCTF95NW9tcnY2NV9zWHRuZ0l3ZmVtck5kZEpUamZyOUk3dUtWaWFoaldmaFpuUV9SakRzejBBRml3eEtQYWkxYnNvNU9aQzlFb0tEcEV1YmtXTnpNZDRJSjMtS3l6TllHMFRMQWpVQVlVbjNlUHYxeHZwbDNfeUZhQTE3TUlHODRDUHZkU2oza1BtRm1EQ0hjZ2xJVUg0WWpYSFhzYWFYbU5PcGZWc3BLLTZZMDRTVDFlVlBabC1fV3NqOUhtQQ?oc=5",
    "date": "2026-10-05",
    "channel": "fricciones_geopoliticas",
    "channel_ui": "⚖️ Fricciones China-Occidente",
    "direction": "NEUTRAL",
    "impact_score": 5.7,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Disputas comerciales y regulatorias en proceso de negociación sin impacto inmediato en la disponibilidad de buques."
  },
  {
    "id": "SHIP-002d6c87",
    "title": "Price to sales forward de Ningbo Daye Garden Machinery Co. Ltd. Class A – SZSE:300879",
    "source": "TradingView",
    "url": "https://news.google.com/rss/articles/CBMinAFBVV95cUxQNXg5azF0bnlZTGtMQW1IamlvVGVmSFJibW84MkMxSkFpdWdTanlwSjZWSnpHVGozQWZBcjhqWEZnY2IxUmhKazg3eXhGSTVpVWFxQnRnY3lwT0UyNjFYdC15dnVjdVNZbXZNTjh0LUxsQ1lIWjF1Tmx5Q1lLYjdVTXZJVXZhcC1XRXlCOG5uMEwwLVdKYS1RNjlnNVo?oc=5",
    "date": "2026-10-05",
    "channel": "china_ports",
    "channel_ui": "🇨🇳 China & Exportaciones",
    "direction": "NEUTRAL",
    "impact_score": 4.6,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Operaciones de carga y zarpe en terminales chinas operando en régimen estándar de calendario."
  },
  {
    "id": "SHIP-05db4433",
    "title": "CMIC Aguascalientes se declara lista para ejecutar el Cuarto Anillo",
    "source": "Líder Empresarial",
    "url": "https://news.google.com/rss/articles/CBMiowFBVV95cUxPaUlYOFE4eTkwWFRvLXoyT21SOGR6djJORGU2U3VTcUI5V0VwcWNoa3hQLVhNazNmbG1mY1k4ZkhnUHl3MVlWU285YUktekxiZnFoVkZHVWZPdTBqZ3FNZTZIOHVibmdYS0lLRWtmRUtESTV4RFpaQ2xhcnhQeWJXNUdvaFBvWHU4ZTRIQ2R0YWNlX0NfdmV1bmRmWWRjX0xyT2Q4?oc=5",
    "date": "2026-10-05",
    "channel": "mexico_ports",
    "channel_ui": "🇲🇽 México & Manzanillo",
    "direction": "NEUTRAL",
    "impact_score": 4.6,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Tiempos de fondeo y desalojo aduanal en rangos históricos promedio (4 a 6 días)."
  },
  {
    "id": "SHIP-0124d998",
    "title": "Canal de Panamá amplía el programa de asignación de cupos para las esclusas Panamax",
    "source": "Yahoo",
    "url": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxNUFE1c1FFNE1EX1hZa19KVWpXd0JJdlVZcEhmbUltdzhock5mT08wOGdjWWxZZVNnQ2hRSlBHbGVTVGpLTllVVmRfeUttMV9aVjhXdDBPbk52ZnhNVGNxVW9FekljZmtybHNCWUhpZkxOTGlVMzBpeFJSRnVRa2FzSm9ZOUE1T1lWZDQweUVXbXEwNmRCZFNFYzE0T2Qwcy1TaWh3SWpMdkxvS1U?oc=5",
    "date": "2026-10-05",
    "channel": "shipping_lines",
    "channel_ui": "🚢 Navieras & Contenedores",
    "direction": "NEUTRAL",
    "impact_score": 4.6,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Mantenimiento de tarifas de flete marítimo dentro de los contratos de servicio vigentes."
  },
  {
    "id": "SHIP-02528a9f",
    "title": "Todos los premios y nominaciones de Evergreen",
    "source": "Filmaffinity",
    "url": "https://news.google.com/rss/articles/CBMickFVX3lxTE5hdnotanAzdHNES2ozSEI2WGlVNk4wcVBfcGxITHJGMTlSRjJLZ3BsSzM0YUFLYnpOTE54LUR6cTVVX0p6ZEg2OGZva0Y4ZFNBS2lwbklLQnRCVmgtSmtES3FoMldqLTh4TW9iZWRzTHc1UQ?oc=5",
    "date": "2026-10-05",
    "channel": "shipping_lines",
    "channel_ui": "🚢 Navieras & Contenedores",
    "direction": "NEUTRAL",
    "impact_score": 4.6,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Mantenimiento de tarifas de flete marítimo dentro de los contratos de servicio vigentes."
  },
  {
    "id": "SHIP-01d16271",
    "title": "GNL de Catar cruza Ormuz con más cargamentos",
    "source": "Inspenet",
    "url": "https://news.google.com/rss/articles/CBMidkFVX3lxTE9LbWd1V0t2RHZoN0Ixa2tkVkdZelRsMmhFSHdIUGRnX1c5VHc1bHloMS1IRm1kT2xNWjlYMXJrb1FoM0xRR3ZLaFZrTkt6MDRnSHNnZTE2bVJpbG9SMHFOdHVEZ3BqZnZHNHk3elItYWVYem9KNXc?oc=5",
    "date": "2026-10-05",
    "channel": "petroleo_bunker",
    "channel_ui": "🛢️ Petróleo & Combustible Bunker",
    "direction": "NEUTRAL",
    "impact_score": 4.6,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Cotizaciones de búnker marino en niveles estables sin alteración inmediata en los recargos por combustible."
  },
  {
    "id": "SHIP-04ae24be",
    "title": "CEO de Aramco advierte que los inventarios mundiales de petróleo siguen bajos ante riesgos en Ormuz",
    "source": "mx.advfn.com",
    "url": "https://news.google.com/rss/articles/CBMi6AFBVV95cUxObUFXVHpWNjRrWEI0bXBxZnhwbVh5dzdkeWxIZVlxdGhTMTNzOFhnNmlOc3c5N2k5STFNR1ZaUF9jX1pwVm1kLVpIdUZyZ19ab3ZBRHdTc1JLRnlSdUNIZ011RzRFNjRoMjc3TzV1bmJfQzBBUmtXaE9pb2FwSi1wdzQzTW1wRlhKQkVfb3JGcTY1NEY5SHRlekQyMVNVNDBXcWRBLWVIM0ZXZXI4NlIzaTNRbml3VW9Bd1R5bEdKaHVobHdZNG13Y18wSnJZNmVjX0hBQVc2Q1VJdmhxclY4SUw1QkxSMVBT?oc=5",
    "date": "2026-10-05",
    "channel": "petroleo_bunker",
    "channel_ui": "🛢️ Petróleo & Combustible Bunker",
    "direction": "NEUTRAL",
    "impact_score": 4.6,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Cotizaciones de búnker marino en niveles estables sin alteración inmediata en los recargos por combustible."
  },
  {
    "id": "SHIP-012d6b57",
    "title": "Aumentan los ataques a petroleros en Ormuz, en medio del repunte de exportaciones de crudo",
    "source": "Infobae",
    "url": "https://news.google.com/rss/articles/CBMi9AFBVV95cUxPcVVsajBJUWVUUGRsR3l6VTRSUWpPM0JsczN1RGhQMjk2SnluM2daNlJpS0l3WmxsQW9UX3F6Q0Zxa21LTUR4dm9JQ2xYWEpqaWJ4UlNGYnhaRTNZM0ZoU3IxVG5ZVjRNSTNqZXFTdUdVdXUwOXktZzcxYUhzckNoMVFnc1hoaGZiWU5uOGNzV2U2Tjl0ZlJjQkYwaUZ2UDY0ckg3aS1sVXYzX0tzUXU3WGtPdFRVTVF5RUVVT1lRZ2xlcFRQMzJIYWkzYnZQeENuTVZTVmI5bkF1Mk9UY3JucHF6T1VUS3JaMVBZVGFaNVJGXzZD0gH0AUFVX3lxTE9xVWxqMElRZVRQZGxHeXpVNFJRak8zQmxzM3VEaFAyOTZKeW4zZ1o2UmlLSXdabGxBb1RfcXpDRnFrbUtNRHh2b0lDbFhYSmppYnhSU0ZieFpFM1kzRmhTcjFUbllWNE1JM2plcVN1R1V1dTA5eS1nNzFhSHNyQ2gxUWdzWGhoZmJZTm44Y3NXZTZOOXRmUmNCRjBpRnZQNjRySDdpLWxVdjNfS3NRdTdYa090VFVNUXlFRVVPWVFnbGVwVFAzMkhhaTNidlB4Q25NVlNWYjluQXUyT1Rjcm5wcXpPVVRLcloxUFlUYVo1UkZfNkM?oc=5",
    "date": "2026-10-05",
    "channel": "petroleo_bunker",
    "channel_ui": "🛢️ Petróleo & Combustible Bunker",
    "direction": "NEUTRAL",
    "impact_score": 4.6,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Cotizaciones de búnker marino en niveles estables sin alteración inmediata en los recargos por combustible."
  },
  {
    "id": "SHIP-05252778",
    "title": "Irán mantiene cerrado el Estrecho de Ormuz y pone condiciones a Estados Unidos para reabrirlo (Redacción Astillero Informa)",
    "source": "julioastillero.com",
    "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxQc0IyRU1ZSnUzLXV3ejE0NTJsX0xaWWhHMHpOY0Y0bUxYMHJiOWdPVmwwYm9Nc0NzN1NHR05EelQyZm9DRklMMXBRVlhvU1Q0NnRqemRBVUR5ZG9nVDk1dU9yeTBidklTUnl6VGhiZldIM05tOG1oVUJqaEFYXzVXc3MwSG5uTlhXMmM2Zks0LTFhdlpVTHdweUJ5RFNINmlDOGtkd1NMSG1kQWhpWEVzdlJFUlZ3VTRYUVloUlVR?oc=5",
    "date": "2026-10-05",
    "channel": "petroleo_bunker",
    "channel_ui": "🛢️ Petróleo & Combustible Bunker",
    "direction": "NEUTRAL",
    "impact_score": 4.6,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Cotizaciones de búnker marino en niveles estables sin alteración inmediata en los recargos por combustible."
  },
  {
    "id": "SHIP-029164de",
    "title": "Suben las apuestas por Carney para el Nobel y Persona del Año tras plantarse a Trump",
    "source": "Los Angeles Times",
    "url": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxQX0dOZ192SkluQk1uem44Z3R1WVBpLTVmd2xiSnFUVkh6dExHd01VMTBMSXF1UzJqUmJQTXVBdm9yT2tFYVZRekVKLUZvSkNCNV80V0V0UDRocFJuNGZ4UllaTUJWX2g4R2N1bmpHRXJuTXdJVW9NWi05bFVHUjJabkFSd1RJc05GX01zbXhhSF9XVFdRZ2Q5T0F2XzJicnF0NWZEbDAxV2NxOWppaUlEZE96eTlrUWVaQkF6YzJOeFlBcHRYdHUxTFB6TTFfM3V5ZExCTmVB?oc=5",
    "date": "2026-10-05",
    "channel": "fricciones_geopoliticas",
    "channel_ui": "⚖️ Fricciones China-Occidente",
    "direction": "ALCISTA_FLETE",
    "impact_score": 4.6,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Aranceles de EE.UU. a China aceleran embarques masivos (front-loading) hacia México para nearshoring, saturando la capacidad de bodega y encareciendo fletes spot."
  },
  {
    "id": "SHIP-03adbdff",
    "title": "Trump verá a Xi esta semana. Llega más debilitado, en parte por el desastre en Irán",
    "source": "Sin Embargo",
    "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxPdDZIQUdTOTNaZjF3eUVJWEV6cFVldVdMYkRtajk5ZC1rZ3lrNERiLVRUUk0zRlN2cW4tNEZjQnFtbFNQa295UHlrMWdFbnJIdEdEdmtleXlNRWkwc1FVRXE5MnBZeGpFZklqYmNmZ0pNai1kbExrbU5iTzhDT1ZyZVdFRjdMZjBKQXV1X21TN0VZbExtSWJNZmdtMnNSQkJ3OGhrSEZ6U1I4cXVHcGwwZzFOTnA5aEE?oc=5",
    "date": "2026-10-05",
    "channel": "fricciones_geopoliticas",
    "channel_ui": "⚖️ Fricciones China-Occidente",
    "direction": "NEUTRAL",
    "impact_score": 4.6,
    "impact_level": "MODERADO",
    "impact_badge": "badge-moderado",
    "transmission": "Disputas comerciales y regulatorias en proceso de negociación sin impacto inmediato en la disponibilidad de buques."
  }
];
